apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>GitOps 101</title>
    </head>
    <body>
      <h1>Hello World from ArgoCD</h1>
      <p>Managed using GitOps</p>
    </body>
    </html>
